### ISSUE TITLE
用户流量可以正常刷新，服务器流量一直为0

### ISSUE THREAD

**Issue by WankkoRee** [MoeGrid/ssrpanel-v2ray#10]
node.id对的呀，按理说没问题才对

**Comment by WankkoRee** [comment]
服务器状态和在线人数可以正常更新

**Comment by MoeGrid** [comment]
服务器流量要要几个小时后才有

**Comment by WankkoRee** [comment]
我知道，但是已经两天了，什么都没有
![default](https://user-images.githubusercontent.com/21287731/48098955-152c6d80-e259-11e8-8e78-198032d2e28a.png)
流量日志是有的
![default](https://user-images.githubusercontent.com/21287731/48098981-207f9900-e259-11e8-8549-1b513b5eb646.png)

**Comment by WankkoRee** [comment]
@aiyahacke

**Comment by MoeGrid** [comment]
计划任务设置没？

**Comment by ghost** [comment]
我也有这个问题，我设置计划任务了，5个节点，前三个正常，后两个也是持续0，偶尔会有几m或者几k，情况跟他一样

**Comment by WankkoRee** [comment]
在修正了我的计划任务的错误后，长时间观察下来，流量可以正常统计，但是数值似乎不准，算了，能用就行

**Comment by Scyllaly** [comment]
@mlgexyz 不准是因为用了锐速这种暴力发包工具导致
