### ISSUE TITLE
使用ws下用户添加失败

### ISSUE THREAD

**Issue by cmmdwl** [MoeGrid/ssrpanel-v2ray#11]
2018/11/06 08:41:05 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNKNOWN: v2ray.com/core/app/proxyman/command: failed to get handler: proxy > v2ray.com/core/app/proxyman/inbound: handler not found: proxy  

{
  "api": {
    "services": [
      "HandlerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "stats": {},
  "inbound": {
    "port": 10087,
    "protocol": "vmess",
    "settings": {
      "clients": []
    },
 "streamSettings":{
      "network":"ws",
      "wsSettings": {
      "path": "/ws", 
"headers": {
"Host": "****.com" 
      }
    }
  }},
  "inboundDetour": [
    {
      "listen": "0.0.0.0",
      "port": 10086,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "0.0.0.0"
      },
      "tag": "api"
    }
  ],
  "log": {
    "access": "./access.log",
    "error": "./error.log",
    "loglevel": "debug"
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "routing": {
    "settings": {
      "rules": [
        {
          "inboundTag": [
            "api"
          ],
          "outboundTag": "api",
          "type": "field"
        }
      ]
    },
    "strategy": "rules"
  },
  "policy": {
    "levels": {
      "1": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    }
  }
}

**Comment by WankkoRee** [comment]
少了个proxy标签，下面是正确的
```
{
	"api": {
		"services": ["HandlerService", "StatsService"],
		"tag": "api"
	},
	"stats": {},
	"inbound": {
		"port": 10087,
		"protocol": "vmess",
		"settings": {
			"clients": []
		},
		"streamSettings": {
			"network": "ws",
			"wsSettings": {
				"path": "/ws",
				"headers": {
					"Host": "****.com"
				}
			}
		},
		"tag": "proxy"
	},
	"inboundDetour": [{
		"listen": "0.0.0.0",
		"port": 10086,
		"protocol": "dokodemo-door",
		"settings": {
			"address": "0.0.0.0"
		},
		"tag": "api"
	}],
	"log": {
		"access": "./access.log",
		"error": "./error.log",
		"loglevel": "debug"
	},
	"outbound": {
		"protocol": "freedom",
		"settings": {}
	},
	"routing": {
		"settings": {
			"rules": [{
				"inboundTag": ["api"],
				"outboundTag": "api",
				"type": "field"
			}]
		},
		"strategy": "rules"
	},
	"policy": {
		"levels": {
			"1": {
				"statsUserUplink": true,
				"statsUserDownlink": true
			}
		}
	}
}
```

**Comment by MoeGrid** [comment]
额

**Comment by cmmdwl** [comment]
emm，好吧，我没检查仔细。。。
