### ISSUE TITLE
在设置成ws模式下mux多路复用似乎不能开启

### ISSUE THREAD

**Issue by cmmdwl** [MoeGrid/ssrpanel-v2ray#12]
启动mux后就出现了500错误，关闭mux后就能正常链接了

**Comment by MoeGrid** [comment]
错误信息有没

**Comment by cmmdwl** [comment]
只有客户端的错误信息

**Comment by cmmdwl** [comment]
emm，客户端不保存信息，服务端信息设置的是info 我看看能不能找到一些什么玩意

**Comment by cmmdwl** [comment]
2018/10/29 17:39:30 [Info] [2884683012] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 106.122.3.172:22529 > v2ray.com/core/proxy/vmess/encoding: invalid user
2018/11/06 19:55:22 [Debug] [2751072262] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:52466
2018/11/06 19:39:49 [Debug] v2ray.com/core/app/log: Logger started
2018/11/06 19:39:49 [Warning] v2ray.com/core: V2Ray 3.50.1 started

**Comment by cmmdwl** [comment]
大概就这些了吧，info太多眼睛都花了，只能找不同了。。。

**Comment by cmmdwl** [comment]
客户端
2018/11/07 03:14:24 [Info] v2ray.com/core/common/mux: dispatching request to udp:8.8.8.8:53
2018/11/07 03:14:24 [Debug] v2ray.com/core/app/dns: updating IP records for domain:cn.centcount.com.
2018/11/07 03:14:24 [Info] [411738479] v2ray.com/core/app/dispatcher: default route for tcp:cn.centcount.com:443
2018/11/07 03:14:24 [Info] [411738479] v2ray.com/core/common/mux: dispatching request to tcp:cn.centcount.com:443
2018/11/07 03:14:32 [Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > EOF

**Comment by MoeGrid** [comment]
v2ray的错，和我的java节点端并没有关系……
