### ISSUE TITLE
连接中断

### ISSUE THREAD

**Issue by Helpayment** [MoeGrid/ssrpanel-v2ray#15]
您好，我用screen守护java -jar ssrpanel-v2ray-0.0.2.jar，1一夜之后，就自动退出了，大佬您是用什么守护的，我的机子是阿里云H1G

**Comment by MoeGrid** [comment]
自动退出指的是java和v2ray进程自动退出还是screen自动退出？

**Comment by Helpayment** [comment]
screen自动退出了，需要重新用screen  java -jar ssrpanel-v2ray-0.0.2.jar，之后我又用supervisord，大佬您用的那个守护进程的

**Comment by MoeGrid** [comment]
我现在就是简单的screen
