### ISSUE TITLE
小白问题。。报错了。。求助

### ISSUE THREAD

**Issue by ghost** [MoeGrid/ssrpanel-v2ray#16]
![image](https://user-images.githubusercontent.com/24932999/48459649-f18f9700-e805-11e8-9aca-bfb9c810c00a.png)

**Comment by ghost** [comment]
嘤嘤嘤 help  应该不是x64和x32的问题吧  。。

**Comment by ghost** [comment]
|  \/  (_)___  __ _| | ____ _  | \ | | ___| |_
 | |\/| | / __|/ _` | |/ / _` | |  \| |/ _ \ __|
 | |  | | \__ \ (_| |   < (_| | | |\  |  __/ |_
 |_|  |_|_|___/\__,_|_|\_\__,_| |_| \_|\___|\__|

V2Ray 4.3 (Po) 20181109
A unified platform for anti-censorship.
2018/11/14 07:07:33 [INFO] cn.moegezi.v2ray.node.process.V2rayDestroyer: V2ray已启动  
2018/11/14 07:07:33 [INFO] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Starting...  
2018/11/14 07:07:35 [INFO] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Start completed.  
2018/11/14 07:07:36 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
2018/11/14 07:07:36 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.00 0.01 0.05  
2018/11/14 07:07:37 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
2018/11/14 07:07:37 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
2018/11/14 07:07:37 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
2018/11/14 07:07:37 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
2018/11/14 07:07:37 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
2018/11/14 07:07:37 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
2018/11/14 07:07:37 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
2018/11/14 07:07:37 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
2018/11/14 07:07:37 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
2018/11/14 07:07:37 [INFO] cn.moegezi.v2ray.node.process.V2rayGrpc: 更新用户: ADD 9 REMOVE 0  
2018/11/14 07:08:35 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 获取用户流量失败

**Comment by MoeGrid** [comment]
json是不是自定义的？没有开放API接口

**Comment by bit-cook** [comment]
ssrpanel老用户没有uuid
在ssrpanel目录下 执行：php artisan upgradeUserVmess ，会给没有生成过vmess_id的用户生成一个vmess_id
