### ISSUE TITLE
建议将能自动化的都自动化一下

### ISSUE THREAD

**Issue by cmmdwl** [MoeGrid/ssrpanel-v2ray#17]
提一个建议，因为java能读数据库，那么也能读取到协议设置，因为v2ray一个服务器只有一个协议设置，因此可以尝试获取而外连接和加密方式等等的东西，那也就能写成自动脚本了

**Comment by MoeGrid** [comment]
懒

**Comment by Scyllaly** [comment]
@aiyahacke 要不是我跑不起来，我也懒得来把你所有closed 的issue全部翻一遍，我sun。。。（手动哭脸）
