### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by cmmdwl** [MoeGrid/ssrpanel-v2ray#2]
[root@host ssrpanel-v2ray]# java -jar /root/ssrpanel-v2ray/ssrpanel-v2ray-0.0.1-SNAPSHOT.jar
  __  __ _           _           _   _      _
 |  \/  (_)___  __ _| | ____ _  | \ | | ___| |_
 | |\/| | / __|/ _` | |/ / _` | |  \| |/ _ \ __|
 | |  | | \__ \ (_| |   < (_| | | |\  |  __/ |_
 |_|  |_|_|___/\__,_|_|\_\__,_| |_| \_|\___|\__|

/root/v2ray-linux-64/v2ray: /root/v2ray-linux-64/v2ray: cannot execute binary file
2018/10/26 12:33:56 [INFO] cn.moegezi.v2ray.node.process.V2rayDestroyer: V2ray已启动  
2018/10/26 12:33:56 [INFO] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Starting...  
2018/10/26 12:33:57 [INFO] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Start completed.  
2018/10/26 12:33:57 [INFO] cn.moegezi.v2ray.node.process.V2rayDestroyer: V2ray已停止  
2018/10/26 12:33:57 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
2018/10/26 12:33:57 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.080.030.01  
2018/10/26 12:33:58 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked  
2018/10/26 12:33:58 [INFO] cn.moegezi.v2ray.node.process.V2rayGrpc: 更新用户: ADD 45 REMOVE 0  
[root@host ssrpanel-v2ray]# /etc/init.d/iptables stop

**Comment by Scyllaly** [comment]
我也是一脸懵逼

**Comment by Scyllaly** [comment]
我倒是没出现你这个问题。就是连不上服务器，服务器也没有任何信息

**Comment by ghost** [comment]
我这也是一模一样的报错

**Comment by Supsfun** [comment]
我也是差不多一样的错误 添加用户失败 config.properties
里面用户等级怎么填？前端对应的是哪个啊

**Comment by cmmdwl** [comment]
2018/10/28 22:12:43 [INFO] cn.moegezi.v2ray.node.process.V2rayDestroyer: V2ray已启动  
/root/v2ray-linux-64/v2ray: /root/v2ray-linux-64/v2ray: cannot execute binary file
2018/10/28 22:12:43 [INFO] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Starting...  
2018/10/28 22:12:43 [INFO] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Start completed.  
2018/10/28 22:12:44 [INFO] cn.moegezi.v2ray.node.process.V2rayDestroyer: V2ray已停止  
2018/10/28 22:12:44 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
2018/10/28 22:12:44 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.00 0.00 0.00  
2018/10/28 22:12:44 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked  
2018/10/28 22:12:44 [INFO] cn.moegezi.v2ray.node.process.V2rayGrpc: 更新用户: ADD 46 REMOVE 0

**Comment by MoeGrid** [comment]
发个config.json和config.properties我看下

**Comment by MoeGrid** [comment]
问题已查明，注意v2ray区分32和64位
