### ISSUE TITLE
使用mkcp报错

### ISSUE THREAD

**Issue by Helpayment** [MoeGrid/ssrpanel-v2ray#20]
大佬，我用mkcp出现报错，我的config.json文件是

{
  "api": {
    "services": [
      "HandlerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "stats": {},
  "inbound": {
    "port": 10088,
    "protocol": "vmess",
    "settings": {
      "clients": []
    },
    "streamSettings": {
      "network": "mkcp"
        "kcpSettings": {
             "header": {
             "type": "wechat-video"
          },
         "uplinkCapacity": 100,
         "downlinkCapacity": 100,
        "tti": 50,
        "writeBufferSize": 2,
        "mtu": 1350,
        "congestion": false,
       "readBufferSize": 2
      },
    },
    "tag": "proxy"
  },
  "inboundDetour": [
    {
      "listen": "0.0.0.0",
      "port": 10086,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "0.0.0.0"
      },
      "tag": "api"
    }
  ],
  "log": {
    "access": "./access.log",
    "error": "./error.log",
    "loglevel": "debug"
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "routing": {
    "settings": {
      "rules": [
        {
          "inboundTag": [
            "api"
          ],
          "outboundTag": "api",
          "type": "field"
        }
      ]
    },
    "strategy": "rules"
  },
  "policy": {
    "levels": {
      "1": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    }
  }
}
您知道哪里参数出问题了吗，谢谢

**Comment by MoeGrid** [comment]
报的啥错？

**Comment by Helpayment** [comment]
{
  "api": {
    "services": [
      "HandlerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "stats": {},
  "inbound": {
    "port": 10088,
    "protocol": "vmess",
    "settings": {
      "clients": []
    },
   "streamSettings": {
        "network": "mkcp", 
        "kcpSettings": {
          "uplinkCapacity": 5,
          "downlinkCapacity": 100,
          "congestion": true,
          "header": {
            "type": "none"
          }
        }
      },
    "tag": "proxy"
  },
  "inboundDetour": [
    {
      "listen": "0.0.0.0",
      "port": 10086,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "0.0.0.0"
      },
      "tag": "api"
    }
  ],
  "log": {
    "access": "./access.log",
    "error": "./error.log",
    "loglevel": "debug"
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "routing": {
    "settings": {
      "rules": [
        {
          "inboundTag": [
            "api"
          ],
          "outboundTag": "api",
          "type": "field"
        }
      ]
    },
    "strategy": "rules"
  },
  "policy": {
    "levels": {
      "1": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    }
  }
}
配置好了，问题已经解决
