### ISSUE TITLE
数据链接SSL 如何添加选项参数

### ISSUE THREAD

**Issue by samac08** [MoeGrid/ssrpanel-v2ray#21]
mysql'5.6以上好像如果不添加禁用或者启用ssl链接数据库参数默认都是SSL 现在需要添加SSL 选项我该怎么写呢 ?
原文:
UTC 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

**Comment by MoeGrid** [comment]
如果不懂java的话，还是建议直接关掉SSL吧……
