### ISSUE TITLE
错误问题 统计问题  求解? log看不到更多信息

### ISSUE THREAD

**Issue by samac08** [MoeGrid/ssrpanel-v2ray#22]
2018/12/10 11:17:10 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0
2018/12/10 11:17:10 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.03 0.02 0.00
2018/12/10 11:18:10 [INFO] cn.moegezi.v2ray.node.process.V2rayGrpc: 获取用户流量: USER user>>>1@v2ray.com>>>traffic>>>uplink TRAFFIC 4225
2018/12/10 11:18:10 [INFO] cn.moegezi.v2ray.node.process.V2rayGrpc: 获取用户流量: USER user>>>1@v2ray.com>>>traffic>>>downlink TRAFFIC 20731
2018/12/10 11:18:10 [ERROR] cn.moegezi.v2ray.node.process.V2rayDao: 记录流量日志: USER_NUM 1 ALL_TRAFFIC 24.37KB
2018/12/10 11:18:10 [ERROR] cn.moegezi.v2ray.node.process.V2rayDao: 更新用户流量信息: USER_NUM 1
2018/12/10 11:18:10 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 1
2018/12/10 11:18:10 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.01 0.02 0.00

**Comment by samac08** [comment]
[https://imgchr.com/i/FJmeY9](url)

**Comment by MoeGrid** [comment]
？

**Comment by MoeGrid** [comment]
这俩error是我写错了，应该是info

**Comment by samac08** [comment]
ok就好 .还以为我哪里设置失误呢! SQL SSL那个我加了参数自己解决了.谢谢!
