### ISSUE TITLE
小建议：执行java -jar xxxxx.jar 之后的信息具体点哈

### ISSUE THREAD

**Issue by ntgeralt** [MoeGrid/ssrpanel-v2ray#24]
你好，感谢你制作的后端方案。有时启动服务后想测试不同用户的联通效果，建议能像SSR启动python server.py之后罗列出所有用户信息就好~

**Comment by MoeGrid** [comment]
这个效果指的是？为了减少远程连数据库的传输数据量，我只获取了用户ID和流量信息，其他用户信息我都没有获取……

**Comment by ghost** [comment]
顺带问下各位大大，我执行java -jar xxx.jar后过一会后就会自动退出，客户端也无法连接，什么原因？感谢各位大大解惑

**Comment by Scyllaly** [comment]
@sosxu 没碰到过哦

**Comment by Scyllaly** [comment]
> 这个效果指的是？为了减少远程连数据库的传输数据量，我只获取了用户ID和流量信息，其他用户信息我都没有获取……

你那个用户等级可以用起来，加个判断，只取大于等于config.propera文件里设定的等级

**Comment by Scyllaly** [comment]
的用户信息

**Comment by Scyllaly** [comment]
酱紫，我面板就可以改进把用户等级搞起来了
