### ISSUE TITLE
时间错误

### ISSUE THREAD

**Issue by samac08** [MoeGrid/ssrpanel-v2ray#25]
同步时间时发现错误 如图  修改成CST 时区吧!

<a href="https://imgchr.com/i/FDlfCd"><img src="https://s1.ax1x.com/2018/12/19/FDlfCd.md.png" alt="FDlfCd.png" border="0" /></a>

**Comment by Scyllaly** [comment]
这个你自己改服务器的时区啊

**Comment by samac08** [comment]
ok 我知道原因了 时区忘记保存了 .

**Comment by PlaneV** [comment]
Java的时区好像有点特别，我是通过环境变量解决这个问题的
 export TZ=Asia/Shanghai
思路出自：
https://blog.csdn.net/youcharming/article/details/43700287
