### ISSUE TITLE
超流量后不能主动断开客户链接

### ISSUE THREAD

**Issue by rzjc** [MoeGrid/ssrpanel-v2ray#4]
2018/10/28 20:07:49 [INFO] cn.moegezi.v2ray.node.process.V2rayGrpc: 更新用户: ADD 0 REMOVE 1
2018/10/28 20:08:49 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户 数: NUMBER 0

remove的这个用户当前尚未断开的v2ray连接仍可以使用，而且不再统计流量了

**Comment by MoeGrid** [comment]
这是因为v2ray有缓存，过几分钟才会断

**Comment by rzjc** [comment]
实测30分钟后连接也没断开
