### ISSUE TITLE
dalao出现这个是怎么回事呢

### ISSUE THREAD

**Issue by Helpayment** [MoeGrid/ssrpanel-v2ray#6]
java -jar /root/ssrpanel-v2ray/ssrpanel-v2ray-0.0.1-SNAPSHOT.jar
Error: Unable to access jarfile /root/ssrpanel-v2ray/ssrpanel-v2ray-0.0.1-SNAPSHOT.jar

**Comment by Supsfun** [comment]
相同的报错

**Comment by MoeGrid** [comment]
无法访问jar文件，看看有没有权限，jar路径是不是写对了，还有不要用0.0.1版本

**Comment by Supsfun** [comment]
> java -jar /root/ssrpanel-v2ray/ssrpanel-v2ray-0.0.1-SNAPSHOT.jar 
> 错误：无法访问jarfile /root/ssrpanel-v2ray/ssrpanel-v2ray-0.0.1-SNAPSHOT.jar

你的这个问题解决了吗

**Comment by MoeGrid** [comment]
# 问题已查明
# 查看jar路径是不是错了！
# 查看jar路径是不是错了！
# 查看jar路径是不是错了！
# 这是常识问题
# 这是常识问题
# 这是常识问题
