### ISSUE TITLE
客户端报错无法连接

### ISSUE THREAD

**Issue by cmmdwl** [MoeGrid/ssrpanel-v2ray#7]
<img width="704" alt="3" src="https://user-images.githubusercontent.com/21263352/47666286-22ed4d80-dbde-11e8-8cc9-43c99a31265e.png">

**Comment by cmmdwl** [comment]
节点信息是面板扫描二维码得到的，服务器关闭了防火墙，并且正常运行，面板设置的是ws模式 有打开tls

**Comment by alienxcn** [comment]
我也遇到了同样的问题。

**Comment by MoeGrid** [comment]
config.json里面的vmess传入连接端口改了没？

**Comment by MoeGrid** [comment]
```
"inbound": {
    "port": 10087, <- 就是这个端口
    "protocol": "vmess",
    "settings": {
      "clients": []
    },
    "streamSettings": {
      "network": "tcp"
    },
    "tag": "proxy"
  },
```

**Comment by alienxcn** [comment]
请问这个端口应该改为什么？

**Comment by MoeGrid** [comment]
你面板设置的什么端口你就改啥啊……这个是客户端连接的端口

**Comment by alienxcn** [comment]
那么在config.properties中的v2ray.grpc.port这个端口也是跟inbound port一致的？

**Comment by MoeGrid** [comment]
看一下readme，我写得很清楚：
v2ray.grpc.port (tag为api的传入连接的端口)

**Comment by alienxcn** [comment]
好的，谢谢。

**Comment by MoeGrid** [comment]
```
"inbound": {
    "port": 10087,
    "protocol": "vmess",
    "settings": {
      "clients": []
    },
    "streamSettings": {
      "network": "tcp"
    },
    "tag": "proxy"
  },
  "inboundDetour": [
    {
      "listen": "0.0.0.0",
      "port": 10086,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "0.0.0.0"
      },
      "tag": "api"
    }
  ],
```
一共就两个传入连接，一个tag是proxy，一个tag为api

**Comment by cmmdwl** [comment]
也就是面板那个接口是忽悠人的了？

**Comment by MoeGrid** [comment]
并不是啊，服务开的是10000端口，面板配置后生成的连接URL二维码和配置文本才是对的啊，不然用户怎么知道你服务配置的是什么端口

**Comment by cmmdwl** [comment]
tcp        0      0 0.0.0.0:8888                0.0.0.0:*                   LISTEN      1034/python         
tcp        0      0 127.0.0.1:25                0.0.0.0:*                   LISTEN      1168/master         
tcp        0      0 0.0.0.0:28037               0.0.0.0:*                   LISTEN      1080/sshd           
tcp        0    464 95.169.11.76:28037          220.160.201.93:51513        ESTABLISHED 14995/sshd          
tcp        0      0 ::1:25                      :::*                        LISTEN      1168/master         
tcp        0      0 :::28037                    :::*                        LISTEN      1080/sshd           
tcp        0      0 :::10086                    :::*                        LISTEN      2057/v2ray          
tcp        0      0 :::10087                    :::*                        LISTEN      2057/v2ray          
不对啊，我这一堆端口都测试了，面板设置端口是443，好奇怪，每一个端口都不能连接，时间问题？
date了一下，时间也是对的啊
